export default function Head() {
  return (
    <>
      <title>Panaverse DAO</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="https://yt3.googleusercontent.com/KwcDbN3NIsrzm9RePTDzT-oO_kfFU9CZnTCYOfQeuD5y_4fKlGWwTynskpY3byYHlx9ro-9_=s900-c-k-c0x00ffffff-no-rj"
      />
    </>
  );
}
